# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uYZlQv9n-RGZdA7MhPyGKRIbOmoGG8W9
"""

!pip install -q scikit-learn matplotlib numpy

from sklearn.datasets import load_digits

digits = load_digits()

print("Data shape", digits.data.shape)
print("Target shape:", digits.target.shape)
print("classes:", set(digits.target))

import matplotlib.pyplot as plt
plt.figure(figsize=(6, 6))

for i in range(4):
    plt.subplot(2, 2, i + 1)
    plt.imshow(digits.images[i], cmap='gray')
    plt.title(f"Label: {digits.target[i]}")
    plt.axis('off')

plt.tight_layout()
plt.show()

from sklearn.model_selection import train_test_split

x = digits.data
y = digits.target

x_train, x_test, y_train, y_test =  train_test_split(
    x, y, test_size=0.2, random_state=42
)
print("training set shape:", x_train.shape)
print("testing set shape:", x_test.shape)

from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors=3)
model.fit(x_train, y_train)
print("Model training is Complete!")

from sklearn.metrics import accuracy_score

y_pred = model.predict(x_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy:.2f}")

print("\nSample Predictions:")
for i in range(5):
  print (f"Predicted: {y_pred[i]}, Actual: {y_test[1]}")